; This is an example of an ini file to use with a game, to make it 
; infinitely more fun to play today - no waiting around...
;
; launch a2m -i golf.ini and it mounts in ../disks from golf.ini
; the 2 world class leaderboard flippy disks.  The ones I reference
; were downloaded from:
; https://www.myabandonware.com/game/world-class-leader-board-kb#Apple%20II

[DiskII]
s6d0 = ../disks/World Class Leader Board (1987)(Access)(Side A).do,../disks/World Class Leader Board (1987)(Access)(Side B).do

[DEBUG]
break.FA62 = execute,map,fast         ; start of ROM execution
  ; The next breakpoint types these characters:
  ; 1 = play, not edit
  ; \r = have swapped disks
  ; O = Old keyboard
  ; Stop here to pick manually but you will need a slow because the demo will
  ;   start, unless you hit 1-4 almost immediately
  ; 1 = 1 player
  ; Stop here and pick the best options now, or just go all the way
  ;   STEFAN\r = Player's name
  ;   A = Amateur
  ;   A=18 holes
  ;   and with that you are tee'd up at the first hole
break.F1BF = execute,map,type=1\rO1STEFAN\rAA
break.55B5 = execute,map,swap=+1    ; switch to the second floppy

; These switch to fast for drawing, and back to slow for playing
break.8577 = execute,map,fast         ; after ball sunk - loading/UI status screen
break.68EA = execute,map,slow         ; before hitting a shot, not on green
break.68DE = execute,map,slow         ; before hitting a shot, on green
break.68D7 = execute,map,fast         ; after shot complete, drawing course
break.581E = execute,map,fast         ; after shot complete, drawing course
