// Apple ][+ and //e Enhanced emulator with assembler
// Stefan Wessels, 2025
// This is free and unencumbered software released into the public domain.

const int unk_help_page_count = 2;
const char *unk_help_text =
"<page 1>\n"
"<#00A000>While emulation is running:\n<#D2D2D2>"
"All keys go to the emulated machine (The Apple ][+), except for the function keys.  Function keys always go to the emulator.\n"
"F1  - Help.\n"
"F9  - Set a breakpoint at the cursor PC.\n"
"F2  - Show / Hide debugger windows.\n"
"F10 - Step over - Single step but not into a JSR call.\n"
"F3  - Toggle emulation speed between 1 MHZ and as fast as possible.\n"
"F11 - Step into - Single step, even into a JSR call.\n"
"F5  - Run (Go) when emulation is stopped.\n"
"F11 + Shift - Step out - Step past RTS at this calling level.\n"
"F6  - Set Program Counter (PC) to cursor PC.\n"
"F12 - Switch between color/mono and also RGB mode if double hires.\n"
"CTRL + SCRLK/PAUSE - Reset the machine.\n"
"F12 + Shift - Switch to Franklin 80 col, if available, on ][+.\n"
"<#00A000>While emulation is stopped:\n<#D2D2D2>"
"If the debug view is visible, all keys go to the debug window over which the mouse is hovered.\n"
"<#0080ff>CPU Window\n<#D2D2D2>"
"Click into a box to edit, i.e. PC, SP, a register or flag and change the value.  Press ENTER to make the change effective.\n"
"<#0080ff>Disassembly window\n<#D2D2D2>"
"<cols 2>"
"CTRL + g - Set cursor PC to address.\tCURSOR UP/DOWN   - Move the cursor PC by a line.\n"
"CTRL + p - Set Apple ][+ PC to the cursor PC .\tPAGE UP/DOWN     - Move the cursor PC by a page.\n"
"CRTL + s - Search symbols.\tHOME/END         - Move top/bottom visible line to cursor PC.\n"
"CRTL + a - Assemble the assembler root file.\tCURSOR LEFT/RIGHT- Reset cursor PC to cpu PC.\n"
"CRTL + SHIFT + a - Set assembler root file.\n\tTAB              - Toggle symbol display (4 possible states).\n"
"<cols1>"
"<#0080ff>Memory window\n<#D2D2D2>"
"Type HEX digits to edit the memory in HEX edit mode, or type any key when editing in ASCII mode.  The address that will be edited is shown at the bottom of the window.\n"
"CRTL + g - Set view start to address.\n"
"CRTL + s - Search symbols.\n"
"CTRL + v - Split the view (up to 16 times).\n"
"CTRL + f - Find by ASCII or HEX.\n"
"CTRL + j - Join a split window with the one below.\n"
"CTRL + n - Find next (forward).\n"
"CTRL + Shift + j - Join a split window with the one above.\n"
"CTRL + Shift + n - Find previous (backwards).\n"
"ALT-0 through ALT-f - Select the memory view (made with CTRL+V).\n"
"CURSOR UP/DOWN - Move the cursor a line up or down.\n"
"CTRL + t - Toggle editing HEX or ASCII at the cursor location.\n"
"PAGE   UP/DOWN - Move the cursor a page up or down.\n"
"HOME/END       - Move the cursor to the start/end of the line.\n"
"HOME/END +CTRL - Move the cursor to the start/end of the view.\n"
"<#0080ff>Miscellaneous window\n<#D2D2D2>"
"Note that this window updates while running, but changes can only be made while the emulation is stopped.\n"
"Miscellaneous SmartPort\n"
"Use the Slot.0 button to boot that disk, when stopped.  Use Eject to eject the disk and Insert will bring up a file chooser to select a new disk.\n"
"Miscellaneous Debug\n"
"The status shows when a Step Over or Step out is actively running.  The Step Cycles show how many cycles the last step took (for profiling) and Total Cycles show all cycles since start (will wrap).\n"
"Breakpoints come in 2 forms.  PC or address (or range).  PC shows up as 4 HEX digits.  Address shows up as R(ead) and or W(rite) access with the address or range in ['s.  With both types, there's also an optional access count (current count/trigger count).  Breakpoints can be edited, enabled/disabled, View jumps to PC of breakpoint (disabled for address) and cleared.  If multiple breakpoints, Clear All removes all breakpoints.\n"
"The call stack shows where the JSR was called and the destination address (and label if available). Click either to set the cursor to that address.\n"
"Miscellaneous Display\n"
"Shows the status of the display soft-switches.  Can be overridden to, for example, see the off-screen page where the application or game may be making changes if page flipping is used.  Turning Override off will reset back to the actual machine status.\n"
"Miscellaneous Language Card\n"
"Shows the status of the language card soft-switches.  Apart from Read ROM / RAM, this is read-only information.\n"
"Configuration\n"
"'s and all entries are optional.  Slot 7 shows up even without an ini file but the Slot= must be set for other smartport drives to show up.  The [Video] section has Slot=<1..7> with 3 being the likely slot, and device = Franklin Ace Display the only accepted setting.\n"
"<page 2>\n"
"The built-in assembler supports these constructs:\n"
"6502 Mnemonics\n"
"All standard opcodes and addressing modes.\n"
"Labels\n"
"Labels start with [a-z|_] and can contain those symbols, and also numbers, and end with a ':'.\n"
"Variables\n"
"Values can be assigned to variables, and variables can be used in expressions.\n"
".commands\n"
"Dot commands are special assembler commands, described below.\n"
"Comments\n"
"The comment character is ';' and everything after ';' on a line is ignored.\n"
"Address\n"
"The address character is '*' and it can be assigned and read.\n"
"Expressions\n"
"The assembler handles complex expressions, rules and precedence as described below.\n"
"Dot Commands:\n"
"Expressions:\n"
".align value\n"
"Aligns data to the next value boundary\n"
"'*' ':' Number variables '('\n"
"Addr, anon labels, num, variables and brackets\n"
".byte value[,value]*\n"
"Outputs value as 8 bits\n"
"'+' '-' '<' '>' '!' '~'\n"
"Unary +, -, lo & hi byte, not and binary not\n"
".word value[,value]*\n"
"Outputs value as 16 bits, lo to hi\n"
"'**'\n"
"Exponentiation (Raise to the power of)\n"
".dword value[,value]*\n"
"Outputs value as 32 bits, lo to hi\n"
"'*' '/' '%'\n"
"Multiply, divide and modulus\n"
".qword value[,value]*\n"
"Outputs value as 64 bits, lo to hi\n"
"'+' '-'\n"
"Additive (plus and minus)\n"
".drow value[,value]*\n"
"Outputs value as 16 bits, hi to lo\n"
"'<<' '>>'\n"
"Shift left and shift right\n"
".drowd value[,value]*\n"
"Outputs value as 32 bits, hi to lo\n"
".lt .le .gt .ge\n"
"for relational <, <=, >, >=\n"
".drowq value[,value]*\n"
"Outputs value as 64 bits, hi to lo\n"
".ne .eq\n"
"for != (not equal) and == (equal)\n"
".for <init>,<cond>,<iter>\n"
"Starts a for loop\n"
"'&'\n"
"Bitwise and\n"
".endfor\n"
"Ends a for loop\n"
"'^'\n"
"Exclusive or\n"
".if <condition>\n"
"Start & true part of a conditional code path\n"
"'|'\n"
"Bitwise or\n"
".else\n"
"False part of a conditional .if code path\n"
"'&&' '||'\n"
"Logical 'and' and 'or'\n"
".endif\n"
"Close conditional .if / .else code path\n"
"'?' ':'\n"
"Ternary Conditional\n"
" [.*[, .*]*]*\n"
"Start a macro with optional arguments\n"
".endmacro\n"
"Ends a macro\n"
"Operator precedence is top down in the table above\n"
".string string[,string]*\n"
"'s\n"
"Variables also take = <expression>, ++ and --\n"
".strcode\n"
"Sets a string character transform expression\n"
"++ and -- are pre operations, even though they have post syntax\n"
"\n"
"Includes the file, filename, at this address\n"
"\n"
"Include a binary file at this address\n"
".org value\n"
"Another way to set the current address\n"
"Number formats:\n"
"String quoted number formats:\n"
"$[0-9a-f]+\n"
"Hexadecimal numbers\n"
"\\x[0-9a-f]+\n"
"Hexadecimal numbers\n"
"0[0-7]+\n"
"Octal numbers\n"
"\\0[0-7]+\n"
"Octal numbers\n"
"%[0-1]+\n"
"Binary numbers\n"
"\\%[0-1]+\n"
"Binary numbers\n"
"[0-9]+\n"
"Decimal numbers\n"
"\\[0-9]+\n"
"Decimal numbers\n"
"Notes:\n"
"The address symbol, '*', can be assigned to, or read.  When read, returns address + 1, so that something like 'lda *' will load the correct address.\n"
"Anonymous labels are unnamed labels, for example ': lda :- ; load from the address where lda resides' or ': beq :- ; branch back to self on eq'\n"
"  Anonymous labels can be read forwards and backwards using + or -.  Examples: 'bra :--' to branch back two ':'s or 'beq :+' to branch to next ':'.\n"
"Ternary conditional '<eval> ? <evaluate if true> : <evaluate if false>' takes expressions in all 3 clauses, so it can be nested.\n"
"Variables all live in a common global scope, so beware of name collisions, especially with .for, .macro and .strcode parameters.\n"
"Since macros take variables, a macro cannot be called with '#5', for example.  The '#' will have to be in the code.\n"
"strcode assigns each non-quoted character in the string to a variable named _ and evaluates the expression given in .strcode and emits the result.\n"
"  example: .strcode _ .ge 65 ? _-65 : _ .ge 41 ? _-41 : _     To resume normal pass-through processing use '.strcode _'.\n"
"' will always emit 'A'.\n"
"A for loop example: '.for _row=0, _row .lt 192, _row++ ; do for block code, up to .endfor, 192 times'.\n"
"Expressions are signed (int64_t) hence .qword or .drowq may emit bad values for numbers greater than $7FFFFFFFFFFFFFFF. An assembler warning will be given.";
